export const FETCH_REWARDS_START = 'FETCH_REWARDS_START';
export const FETCH_REWARDS_SUCCESS = 'FETCH_REWARDS_SUCCESS';
export const FETCH_REWARDS_FAILURE = 'FETCH_REWARDS_FAILURE';
export const COLLECT_REWARD = 'COLLECT_REWARD';